[project]
name = "fed-scraper"
version = "0.1.0"
description = "Federal Reserve speeches and testimony scraper"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "httpx>=0.28.1",
    "lxml>=5.3.0",
    "python-dotenv>=1.1.1",
    "qdrant-client[fastembed]>=1.15.1",
]
